kind: pipeline
type: docker
name: drone-test

steps:
  - name: build
    image: golang:1.17
    commands:
      - go env -w GO111MODULE=on
      - go env -w GOPROXY="https://goproxy.cn,direct"
      - go build -o main main.go

trigger:
  branch:
    - master
  event:
    - push
